name: 'spain_weather'
version: '1.0.0'
config-version: 2

profile: 'spain_weather'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  spain_weather:
    staging:
      +materialized: view
    marts:
      +materialized: table